name: clang-tidy check

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

jobs:
  clang-tidy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Setup ESP-IDF
      uses: espressif/esp-idf-action@v2
      with:
        version: 'latest'

    - name: Install clang-tidy
      run: sudo apt-get update && sudo apt-get install -y clang-tidy

    - name: Configure build (generate compile_commands.json)
      run: idf.py fullclean && idf.py build

    - name: Run clang-tidy on source files
      run: |
        cd build
        # Run clang-tidy with the compile commands database
        clang-tidy -p . $(find ../main ../components -name '*.c' -o -name '*.cpp') --quiet